### ISSUE TITLE
Enhancement allowing to pass start/end date as environment variables in wps.run/run.sh

### ISSUE THREAD

**Issue by laurentganne** [cima-lexis/wps.docker#1]
In LEXIS orchestration context, it is easier to use environment variables when dealing with docker containers.
Could it be possible to change `wps.run/run.sh` to allow to pass environment variables, in addition to arguments?

We could for example replace in ``wps.run/run.sh``:
```
export start=$1
export end=$2
```
by:
```
if [ "$#" -eq 2 ]; then
  export start=$1
  export end=$2
else
  export start="${WPS_START_DATE}"
  export end="${WPS_END_DATE}"
fi
```

**Comment by parro-it** [comment]
Hi Laurent, seems both simple and useful, I'll implement it.
I think I can work on this today, and meanwhile, I'm running the WRF run
on the files you sent me.

**Comment by parro-it** [comment]
I changed the script as you suggested. 
I'm doing some other small changes, today I'll test all
and send you an email when finished.
